// "How the city works" — player-facing guide copy, 7 languages.
// Numbers are NOT hard-coded here: `{placeholders}` are filled from @guttercaps/economy
// in Guide.tsx, so the guide can never drift from the on-chain parameters.
// Deliberately omitted (not player knowledge): anti-fraud thresholds, device/IP limits,
// oracle internals, emission-guard formula, team allocation, model assumptions.

export interface GuideSection { id: string; title: string; lead: string; body: string[] }
export interface GuideCopy { title: string; subtitle: string; toc: string; sections: GuideSection[]; outro: string }

const en: GuideCopy = {
  title: 'How the city works',
  subtitle: 'A street guide to Gutter City — caps, fusion, trade, stake and the coin that ties it all together.',
  toc: 'On this wall',
  sections: [
    { id: 'collect', title: 'Collect', lead: 'Every cap is a piece of a district’s story.',
      body: ['Gutter City has {districts} districts, and each district tells its story in nine caps — from a scratched zinc Common to a prism-bright Diamond. One cap per rarity, nine rarities per district.',
        'Complete a district and it pays you back: every full set strengthens your staked caps, and the rarest sets become status on the leaderboard. Duplicates are never dead weight — they are fuel for fusion.'] },
    { id: 'packs', title: 'Packs', lead: 'Every pack is sealed on-chain and opened with verifiable randomness.',
      body: ['Starter — {starter}, {starterChips} caps, one per day: the easiest way into the city. Standard — {standard} or {standardCg}, {standardChips} caps. Premium — {premium} or {premiumCg}, {premiumChips} caps with a guaranteed Rare. Limited — {limited}, event districts only.',
        'Bad luck has a ceiling: Standard and Premium packs carry a pity counter that guarantees a Legend. Every opening can be checked on the Verify page — nobody, including us, can pick what drops.'] },
    { id: 'fusion', title: 'Fusion', lead: 'Three caps of one rarity melt into one cap of the next.',
      body: ['Up to Epic, fusion always works. The steps alternate: to climb half a tier (Common → Common+) any three caps will do and the result keeps the first cap’s district; to climb a full tier (Common+ → Rare) all three must come from the same district.',
        'From Epic upward the flood gets wild: fusion can fail, but one material always comes back. A Charge Booster adds +{boosterBonus} pp (up to {boosterCap}%) — boosters are earned in quests and the arena, never sold.',
        'Each fusion costs a small $CG fee, starting at {fusionFee0} — and that fee is burned forever. Fresh high-tier results rest for a while before they can be fused or listed again.'] },
    { id: 'trade', title: 'Trade', lead: 'The market is where districts meet.',
      body: ['List any free cap for SOL, USDC or SKR. The cap waits in escrow — the buyer gets the cap, you get paid, in one transaction. Listing costs {listingFee}.',
        'On every sale {marketFee} goes to the city and {royalty} to the artists. Part of the city’s share buys back $CG and burns it, so every trade makes the coin a little scarcer.'] },
    { id: 'stake', title: 'Stake', lead: 'Put caps and coins to work while you sleep.',
      body: ['Staked caps earn a share of the daily cap-staking pool. The rarer and higher-level the cap, the bigger the share; completed district sets add a bonus. The pool is shared — it does not grow when more caps join, so early and rare caps matter.',
        '$CG can be staked too: flexible, or locked for 30, 90 or 180 days for a bigger multiplier (×{d30}, ×{d90}, ×{d180}). Leaving a lock early burns part of the stake ({p30}/{p90}/{p180}).',
        'A staked cap is locked: it cannot be fused, listed or used in the arena until you unstake it.'] },
    { id: 'coin', title: 'The $CG coin', lead: 'Earned on the street, spent on the street.',
      body: ['$CG is the city’s coin. It is never sold by the studio — you earn it in daily and weekly quests, arena matches and seasons, staking and events, or buy it from other players.',
        'You spend it on packs, fusion fees, arena wagers and cosmetics. The daily supply is limited and follows the city’s activity: the more the city burns, the more room there is for new coins — and when the streets are quiet, the tap closes.'] },
    { id: 'burn', title: 'What burns', lead: 'Scarcity is what keeps value on the wall.',
      body: ['Coins burn: every fusion fee, most of the price of packs bought with $CG, listing fees, part of market and arena fees and early-unstake penalties are destroyed for good.',
        'Caps burn too: each fusion turns three caps into one, so the supply of every rarity keeps shrinking as players climb. The higher the tier, the fewer will ever exist.'] },
    { id: 'free', title: 'Free caps', lead: 'The city rewards those who show up.',
      body: ['Quests pay $CG every day. Keep a 7-day streak for a free cap, finish all weeklies for a better one, and hit big milestones — 500 arena wins, a full district set — for rare rewards. Stakers also enter a weekly raffle for Rare–Epic caps.',
        'Free caps are bound to your wallet for a few days before they can be traded — they are yours to play, not to flip.'] },
  ],
  outro: 'Every rule on this wall is enforced by the programs on Solana — the same for everyone.',
};

const ru: GuideCopy = {
  title: 'Как устроен город',
  subtitle: 'Уличный путеводитель по Gutter City: фишки, слияние, торговля, стейкинг и монета, которая связывает всё вместе.',
  toc: 'На этой стене',
  sections: [
    { id: 'collect', title: 'Коллекция', lead: 'Каждая фишка — страница истории своего района.',
      body: ['В Gutter City {districts} районов, и каждый рассказывает свою историю девятью фишками — от исцарапанного цинкового Common до переливчатого Diamond. Одна фишка на каждую редкость, девять редкостей в районе.',
        'Собранный район окупается: каждый полный набор усиливает ваши фишки в стейкинге, а редкие наборы становятся статусом в рейтинге. Дубликаты не пылятся — это топливо для слияния.'] },
    { id: 'packs', title: 'Паки', lead: 'Каждый пак запечатан в блокчейне и вскрывается проверяемой случайностью.',
      body: ['Starter — {starter}, {starterChips} фишки, один в день: самый лёгкий вход в город. Standard — {standard} или {standardCg}, {standardChips} фишки. Premium — {premium} или {premiumCg}, {premiumChips} фишек с гарантированной Rare. Limited — {limited}, только районы события.',
        'У невезения есть потолок: в Standard и Premium работает счётчик, который гарантирует Legend. Любое вскрытие можно проверить на странице «Проверка» — никто, включая нас, не выбирает, что выпадет.'] },
    { id: 'fusion', title: 'Слияние', lead: 'Три фишки одной редкости сплавляются в одну следующей.',
      body: ['До Epic слияние срабатывает всегда. Шаги чередуются: чтобы подняться на полступени (Common → Common+), подойдут любые три фишки, а результат останется в районе первой; чтобы подняться на целую ступень (Common+ → Rare), все три должны быть из одного района.',
        'Начиная с Epic, поток становится непредсказуемым: слияние может не удаться, но одна фишка всегда возвращается. Заряд-бустер добавляет +{boosterBonus} п.п. (до {boosterCap}%) — бустеры зарабатываются в квестах и на арене, их не продают.',
        'Каждое слияние стоит небольшую комиссию в $CG — от {fusionFee0}, и эта комиссия сгорает навсегда. Свежие фишки высоких редкостей какое-то время отдыхают, прежде чем их можно снова сплавить или выставить.'] },
    { id: 'trade', title: 'Торговля', lead: 'Маркет — место, где встречаются районы.',
      body: ['Выставляйте любую свободную фишку за SOL, USDC или SKR. Фишка ждёт на эскроу: покупатель получает фишку, вы — оплату, в одной транзакции. Выставление стоит {listingFee}.',
        'С каждой продажи {marketFee} уходит городу и {royalty} — художникам. Часть доли города выкупает $CG и сжигает, так что каждая сделка делает монету чуть дефицитнее.'] },
    { id: 'stake', title: 'Стейкинг', lead: 'Пусть фишки и монеты работают, пока вы спите.',
      body: ['Фишки в стейкинге получают долю дневного пула. Чем реже и прокачаннее фишка, тем больше доля; собранные наборы районов дают бонус. Пул общий — он не растёт, когда фишек становится больше, поэтому ранние и редкие фишки весят больше.',
        '$CG тоже можно застейкать: свободно или с блокировкой на 30, 90 или 180 дней ради большего множителя (×{d30}, ×{d90}, ×{d180}). Досрочный выход из блокировки сжигает часть суммы ({p30}/{p90}/{p180}).',
        'Фишка в стейкинге заблокирована: её нельзя сплавить, выставить или взять на арену, пока вы её не заберёте.'] },
    { id: 'coin', title: 'Монета $CG', lead: 'Заработана на улице — потрачена на улице.',
      body: ['$CG — монета города. Студия её не продаёт: её зарабатывают в ежедневных и еженедельных квестах, матчах и сезонах арены, стейкинге и событиях или покупают у других игроков.',
        'Её тратят на паки, комиссии слияния, ставки на арене и косметику. Дневной выпуск ограничен и следует за жизнью города: чем больше город сжигает, тем больше места для новых монет, а когда на улицах тихо — кран закрывается.'] },
    { id: 'burn', title: 'Что сгорает', lead: 'Дефицит — то, что держит ценность на стене.',
      body: ['Сгорают монеты: каждая комиссия слияния, большая часть цены паков за $CG, плата за выставление, часть комиссий маркета и арены и штрафы за досрочный выход из стейкинга уничтожаются навсегда.',
        'Сгорают и фишки: каждое слияние превращает три фишки в одну, поэтому запас каждой редкости тает по мере того, как игроки поднимаются выше. Чем выше ступень, тем меньше таких фишек вообще будет существовать.'] },
    { id: 'free', title: 'Бесплатные фишки', lead: 'Город вознаграждает тех, кто приходит.',
      body: ['Квесты каждый день платят $CG. Держите серию 7 дней — получите фишку, закройте все еженедельные — получите фишку получше, а за большие вехи — 500 побед на арене, полный набор района — редкие награды. Стейкеры участвуют в еженедельном розыгрыше фишек Rare–Epic.',
        'Бесплатные фишки несколько дней привязаны к кошельку, прежде чем их можно продать: ими играют, а не перепродают.'] },
  ],
  outro: 'Каждое правило на этой стене исполняют программы в Solana — одинаково для всех.',
};

const es: GuideCopy = {
  title: 'Cómo funciona la ciudad',
  subtitle: 'Guía callejera de Gutter City: caps, fusión, comercio, staking y la moneda que lo une todo.',
  toc: 'En este muro',
  sections: [
    { id: 'collect', title: 'Colecciona', lead: 'Cada cap es una página de la historia de su barrio.',
      body: ['Gutter City tiene {districts} barrios y cada uno cuenta su historia en nueve caps: desde un Common de zinc rayado hasta un Diamond prismático. Un cap por rareza, nueve rarezas por barrio.',
        'Completar un barrio tiene premio: cada set completo potencia tus caps en staking y los sets más raros son estatus en el ranking. Los duplicados nunca sobran: son combustible para la fusión.'] },
    { id: 'packs', title: 'Packs', lead: 'Cada pack está sellado on-chain y se abre con azar verificable.',
      body: ['Starter — {starter}, {starterChips} caps, uno al día: la entrada más fácil a la ciudad. Standard — {standard} o {standardCg}, {standardChips} caps. Premium — {premium} o {premiumCg}, {premiumChips} caps con un Rare garantizado. Limited — {limited}, solo barrios de evento.',
        'La mala suerte tiene techo: Standard y Premium llevan un contador que garantiza un Legend. Cada apertura se puede comprobar en la página Verificar: nadie, ni nosotros, elige lo que sale.'] },
    { id: 'fusion', title: 'Fusión', lead: 'Tres caps de una rareza se funden en uno de la siguiente.',
      body: ['Hasta Epic, la fusión siempre funciona. Los pasos se alternan: para subir medio nivel (Common → Common+) sirven tres caps cualesquiera y el resultado conserva el barrio del primero; para subir un nivel completo (Common+ → Rare) los tres deben ser del mismo barrio.',
        'Desde Epic la corriente se vuelve salvaje: la fusión puede fallar, pero siempre vuelve un material. Un Charge Booster suma +{boosterBonus} pp (hasta {boosterCap}%): se gana en misiones y en la arena, nunca se vende.',
        'Cada fusión cuesta una pequeña tarifa en $CG, desde {fusionFee0}, y esa tarifa se quema para siempre. Los resultados de nivel alto descansan un tiempo antes de volver a fusionarse o listarse.'] },
    { id: 'trade', title: 'Comercia', lead: 'El mercado es donde se cruzan los barrios.',
      body: ['Pon a la venta cualquier cap libre por SOL, USDC o SKR. El cap espera en escrow: el comprador recibe el cap y tú el pago, en una sola transacción. Listar cuesta {listingFee}.',
        'En cada venta, {marketFee} va a la ciudad y {royalty} a los artistas. Parte de la cuota de la ciudad recompra $CG y lo quema, así que cada operación hace la moneda un poco más escasa.'] },
    { id: 'stake', title: 'Staking', lead: 'Pon a trabajar caps y monedas mientras duermes.',
      body: ['Los caps en staking ganan una parte del fondo diario. Cuanto más raro y más nivel, mayor parte; los sets de barrio completos dan bonus. El fondo es compartido: no crece cuando entran más caps, así que los caps raros y tempranos pesan más.',
        'También puedes hacer staking de $CG: flexible o bloqueado 30, 90 o 180 días para un multiplicador mayor (×{d30}, ×{d90}, ×{d180}). Salir antes quema parte del depósito ({p30}/{p90}/{p180}).',
        'Un cap en staking queda bloqueado: no se puede fusionar, listar ni usar en la arena hasta retirarlo.'] },
    { id: 'coin', title: 'La moneda $CG', lead: 'Se gana en la calle y se gasta en la calle.',
      body: ['$CG es la moneda de la ciudad. El estudio nunca la vende: se gana en misiones diarias y semanales, partidas y temporadas de arena, staking y eventos, o se compra a otros jugadores.',
        'Se gasta en packs, tarifas de fusión, apuestas en la arena y cosméticos. La emisión diaria es limitada y sigue la actividad de la ciudad: cuanto más se quema, más espacio hay para monedas nuevas; cuando las calles están tranquilas, el grifo se cierra.'] },
    { id: 'burn', title: 'Lo que se quema', lead: 'La escasez mantiene el valor en el muro.',
      body: ['Se queman monedas: cada tarifa de fusión, la mayor parte del precio de los packs pagados en $CG, las tarifas de listado, parte de las comisiones del mercado y la arena y las penalizaciones por salir antes del staking.',
        'También se queman caps: cada fusión convierte tres en uno, así que la oferta de cada rareza se reduce a medida que los jugadores suben. Cuanto más alto el nivel, menos existirán jamás.'] },
    { id: 'free', title: 'Caps gratis', lead: 'La ciudad premia a quien aparece.',
      body: ['Las misiones pagan $CG cada día. Mantén una racha de 7 días para un cap gratis, completa todas las semanales para uno mejor y alcanza grandes hitos —500 victorias en la arena, un barrio completo— para premios raros. Quien hace staking entra en un sorteo semanal de caps Rare–Epic.',
        'Los caps gratis quedan ligados a tu cartera unos días antes de poder venderse: son para jugar, no para revender.'] },
  ],
  outro: 'Cada regla de este muro la cumplen los programas en Solana, igual para todos.',
};

const pt: GuideCopy = {
  title: 'Como a cidade funciona',
  subtitle: 'Guia de rua de Gutter City: caps, fusão, comércio, staking e a moeda que liga tudo.',
  toc: 'Neste muro',
  sections: [
    { id: 'collect', title: 'Colecione', lead: 'Cada cap é uma página da história do seu bairro.',
      body: ['Gutter City tem {districts} bairros, e cada um conta sua história em nove caps — de um Common de zinco arranhado a um Diamond prismático. Um cap por raridade, nove raridades por bairro.',
        'Completar um bairro compensa: cada set completo fortalece seus caps em staking, e os sets mais raros viram status no ranking. Duplicatas nunca são peso morto — são combustível para a fusão.'] },
    { id: 'packs', title: 'Packs', lead: 'Cada pack é selado on-chain e aberto com aleatoriedade verificável.',
      body: ['Starter — {starter}, {starterChips} caps, um por dia: a entrada mais fácil na cidade. Standard — {standard} ou {standardCg}, {standardChips} caps. Premium — {premium} ou {premiumCg}, {premiumChips} caps com um Rare garantido. Limited — {limited}, só bairros de evento.',
        'O azar tem teto: Standard e Premium têm um contador que garante um Legend. Toda abertura pode ser conferida na página Verificar — ninguém, nem nós, escolhe o que sai.'] },
    { id: 'fusion', title: 'Fusão', lead: 'Três caps de uma raridade viram um da próxima.',
      body: ['Até Epic, a fusão sempre funciona. Os passos se alternam: para subir meio nível (Common → Common+) servem quaisquer três caps e o resultado fica no bairro do primeiro; para subir um nível inteiro (Common+ → Rare) os três precisam ser do mesmo bairro.',
        'A partir de Epic a enxurrada fica imprevisível: a fusão pode falhar, mas um material sempre volta. Um Charge Booster soma +{boosterBonus} pp (até {boosterCap}%) — boosters são ganhos em missões e na arena, nunca vendidos.',
        'Cada fusão custa uma pequena taxa em $CG, a partir de {fusionFee0}, e essa taxa é queimada para sempre. Resultados de nível alto descansam um tempo antes de poderem ser fundidos ou listados de novo.'] },
    { id: 'trade', title: 'Negocie', lead: 'O mercado é onde os bairros se encontram.',
      body: ['Liste qualquer cap livre por SOL, USDC ou SKR. O cap espera em escrow — o comprador recebe o cap e você recebe o pagamento, numa só transação. Listar custa {listingFee}.',
        'Em cada venda, {marketFee} vai para a cidade e {royalty} para os artistas. Parte da fatia da cidade recompra $CG e queima, então cada negócio deixa a moeda um pouco mais escassa.'] },
    { id: 'stake', title: 'Staking', lead: 'Coloque caps e moedas para trabalhar enquanto você dorme.',
      body: ['Caps em staking ganham uma parte do fundo diário. Quanto mais raro e mais evoluído, maior a parte; sets de bairro completos dão bônus. O fundo é compartilhado — não cresce quando entram mais caps, então caps raros e antigos pesam mais.',
        '$CG também pode ir para staking: flexível ou travado por 30, 90 ou 180 dias para um multiplicador maior (×{d30}, ×{d90}, ×{d180}). Sair antes queima parte do valor ({p30}/{p90}/{p180}).',
        'Um cap em staking fica travado: não pode ser fundido, listado ou usado na arena até ser retirado.'] },
    { id: 'coin', title: 'A moeda $CG', lead: 'Ganha na rua, gasta na rua.',
      body: ['$CG é a moeda da cidade. O estúdio nunca a vende — ela é ganha em missões diárias e semanais, partidas e temporadas da arena, staking e eventos, ou comprada de outros jogadores.',
        'Ela é gasta em packs, taxas de fusão, apostas na arena e cosméticos. A emissão diária é limitada e acompanha a atividade da cidade: quanto mais se queima, mais espaço para moedas novas — e quando as ruas estão calmas, a torneira fecha.'] },
    { id: 'burn', title: 'O que queima', lead: 'A escassez mantém o valor no muro.',
      body: ['Moedas queimam: toda taxa de fusão, a maior parte do preço de packs pagos em $CG, taxas de listagem, parte das taxas do mercado e da arena e as multas por sair cedo do staking são destruídas para sempre.',
        'Caps também queimam: cada fusão transforma três em um, então a oferta de cada raridade encolhe conforme os jogadores sobem. Quanto mais alto o nível, menos deles existirão.'] },
    { id: 'free', title: 'Caps grátis', lead: 'A cidade recompensa quem aparece.',
      body: ['Missões pagam $CG todos os dias. Mantenha uma sequência de 7 dias para um cap grátis, complete todas as semanais para um melhor e alcance grandes marcos — 500 vitórias na arena, um bairro completo — para prêmios raros. Quem faz staking entra num sorteio semanal de caps Rare–Epic.',
        'Caps grátis ficam presos à sua carteira por alguns dias antes de poderem ser vendidos — são para jogar, não para revender.'] },
  ],
  outro: 'Cada regra deste muro é executada pelos programas na Solana — igual para todos.',
};

const vi: GuideCopy = {
  title: 'Thành phố vận hành thế nào',
  subtitle: 'Cẩm nang đường phố Gutter City: nắp, hợp nhất, giao dịch, staking và đồng xu gắn kết tất cả.',
  toc: 'Trên bức tường này',
  sections: [
    { id: 'collect', title: 'Sưu tầm', lead: 'Mỗi chiếc nắp là một trang trong câu chuyện của khu phố.',
      body: ['Gutter City có {districts} khu phố, mỗi khu kể câu chuyện của mình qua chín chiếc nắp — từ Common kẽm trầy xước đến Diamond lấp lánh. Mỗi độ hiếm một nắp, chín độ hiếm mỗi khu.',
        'Hoàn thành một khu phố sẽ được đền đáp: mỗi bộ đầy đủ tăng sức mạnh cho nắp đang stake, và các bộ hiếm nhất là danh vọng trên bảng xếp hạng. Nắp trùng không bao giờ vô dụng — chúng là nhiên liệu cho hợp nhất.'] },
    { id: 'packs', title: 'Gói', lead: 'Mỗi gói được niêm phong on-chain và mở bằng ngẫu nhiên có thể kiểm chứng.',
      body: ['Starter — {starter}, {starterChips} nắp, mỗi ngày một gói: cách dễ nhất vào thành phố. Standard — {standard} hoặc {standardCg}, {standardChips} nắp. Premium — {premium} hoặc {premiumCg}, {premiumChips} nắp, chắc chắn có Rare. Limited — {limited}, chỉ khu phố sự kiện.',
        'Xui xẻo cũng có giới hạn: Standard và Premium có bộ đếm đảm bảo một Legend. Mọi lần mở đều kiểm tra được ở trang Xác minh — không ai, kể cả chúng tôi, chọn được thứ rơi ra.'] },
    { id: 'fusion', title: 'Hợp nhất', lead: 'Ba nắp cùng độ hiếm nung chảy thành một nắp bậc tiếp theo.',
      body: ['Đến Epic, hợp nhất luôn thành công. Các bước xen kẽ: lên nửa bậc (Common → Common+) dùng ba nắp bất kỳ và kết quả giữ khu phố của nắp đầu tiên; lên trọn một bậc (Common+ → Rare) cả ba phải cùng một khu phố.',
        'Từ Epic trở lên dòng lũ trở nên khó lường: hợp nhất có thể thất bại, nhưng luôn hoàn lại một nguyên liệu. Charge Booster cộng +{boosterBonus} điểm % (tối đa {boosterCap}%) — booster kiếm được từ nhiệm vụ và đấu trường, không bao giờ bán.',
        'Mỗi lần hợp nhất tốn một khoản phí nhỏ bằng $CG, từ {fusionFee0}, và phí đó bị đốt vĩnh viễn. Nắp bậc cao mới tạo cần nghỉ một thời gian trước khi hợp nhất hoặc rao bán lại.'] },
    { id: 'trade', title: 'Giao dịch', lead: 'Chợ là nơi các khu phố gặp nhau.',
      body: ['Rao bán bất kỳ nắp rảnh nào lấy SOL, USDC hoặc SKR. Nắp chờ trong ký quỹ — người mua nhận nắp, bạn nhận tiền, trong một giao dịch. Phí rao bán {listingFee}.',
        'Mỗi lần bán, {marketFee} về thành phố và {royalty} cho nghệ sĩ. Một phần của thành phố được dùng mua lại và đốt $CG, nên mỗi giao dịch làm đồng xu khan hiếm hơn một chút.'] },
    { id: 'stake', title: 'Staking', lead: 'Để nắp và xu làm việc khi bạn ngủ.',
      body: ['Nắp đang stake nhận một phần quỹ hằng ngày. Nắp càng hiếm và cấp càng cao, phần càng lớn; bộ khu phố hoàn chỉnh cho thêm thưởng. Quỹ là chung — không tăng khi có thêm nắp, nên nắp hiếm và đến sớm có trọng số lớn hơn.',
        '$CG cũng có thể stake: linh hoạt, hoặc khóa 30, 90, 180 ngày để có hệ số cao hơn (×{d30}, ×{d90}, ×{d180}). Rút sớm sẽ đốt một phần số tiền ({p30}/{p90}/{p180}).',
        'Nắp đang stake bị khóa: không thể hợp nhất, rao bán hay mang vào đấu trường cho đến khi rút ra.'] },
    { id: 'coin', title: 'Đồng $CG', lead: 'Kiếm trên phố, tiêu trên phố.',
      body: ['$CG là đồng xu của thành phố. Studio không bao giờ bán nó — bạn kiếm được từ nhiệm vụ hằng ngày và hằng tuần, trận đấu và mùa giải đấu trường, staking và sự kiện, hoặc mua từ người chơi khác.',
        'Bạn tiêu nó cho gói, phí hợp nhất, cược đấu trường và vật phẩm trang trí. Lượng phát hành mỗi ngày có giới hạn và đi theo nhịp sống thành phố: càng đốt nhiều, càng có chỗ cho xu mới — khi phố vắng, vòi sẽ khóa lại.'] },
    { id: 'burn', title: 'Thứ bị đốt', lead: 'Sự khan hiếm giữ giá trị trên bức tường.',
      body: ['Xu bị đốt: mọi phí hợp nhất, phần lớn giá gói mua bằng $CG, phí rao bán, một phần phí chợ và đấu trường cùng tiền phạt rút stake sớm đều bị hủy vĩnh viễn.',
        'Nắp cũng bị đốt: mỗi lần hợp nhất biến ba nắp thành một, nên nguồn cung mỗi độ hiếm cứ thu hẹp khi người chơi leo lên. Bậc càng cao, số lượng từng tồn tại càng ít.'] },
    { id: 'free', title: 'Nắp miễn phí', lead: 'Thành phố thưởng cho người có mặt.',
      body: ['Nhiệm vụ trả $CG mỗi ngày. Giữ chuỗi 7 ngày để nhận một nắp miễn phí, hoàn thành mọi nhiệm vụ tuần để nhận nắp tốt hơn, và đạt các cột mốc lớn — 500 trận thắng, một bộ khu phố hoàn chỉnh — để nhận phần thưởng hiếm. Người stake được tham gia quay thưởng nắp Rare–Epic hằng tuần.',
        'Nắp miễn phí gắn với ví của bạn vài ngày trước khi có thể bán — để chơi, không phải để lướt sóng.'] },
  ],
  outro: 'Mọi luật trên bức tường này đều do các chương trình trên Solana thực thi — như nhau với tất cả.',
};

const id: GuideCopy = {
  title: 'Cara kota bekerja',
  subtitle: 'Panduan jalanan Gutter City: caps, fusi, dagang, staking, dan koin yang menyatukan semuanya.',
  toc: 'Di tembok ini',
  sections: [
    { id: 'collect', title: 'Koleksi', lead: 'Setiap cap adalah satu halaman cerita distriknya.',
      body: ['Gutter City punya {districts} distrik, dan tiap distrik bercerita lewat sembilan cap — dari Common seng tergores sampai Diamond berkilau prisma. Satu cap per kelangkaan, sembilan kelangkaan per distrik.',
        'Menuntaskan distrik itu menguntungkan: setiap set lengkap memperkuat cap yang di-stake, dan set paling langka jadi gengsi di papan peringkat. Duplikat tidak pernah sia-sia — itu bahan bakar fusi.'] },
    { id: 'packs', title: 'Pack', lead: 'Setiap pack disegel on-chain dan dibuka dengan keacakan yang bisa diverifikasi.',
      body: ['Starter — {starter}, {starterChips} cap, satu per hari: jalan termudah masuk kota. Standard — {standard} atau {standardCg}, {standardChips} cap. Premium — {premium} atau {premiumCg}, {premiumChips} cap dengan Rare terjamin. Limited — {limited}, khusus distrik event.',
        'Nasib sial ada batasnya: Standard dan Premium punya penghitung yang menjamin Legend. Setiap pembukaan bisa dicek di halaman Verifikasi — tak ada yang bisa memilih hasilnya, termasuk kami.'] },
    { id: 'fusion', title: 'Fusi', lead: 'Tiga cap satu kelangkaan melebur jadi satu cap tingkat berikutnya.',
      body: ['Sampai Epic, fusi selalu berhasil. Langkahnya bergantian: naik setengah tingkat (Common → Common+) boleh tiga cap apa saja dan hasilnya ikut distrik cap pertama; naik satu tingkat penuh (Common+ → Rare) ketiganya harus dari distrik yang sama.',
        'Mulai Epic arusnya liar: fusi bisa gagal, tapi satu bahan selalu kembali. Charge Booster menambah +{boosterBonus} poin % (maks {boosterCap}%) — booster didapat dari misi dan arena, tidak pernah dijual.',
        'Setiap fusi dikenai biaya kecil dalam $CG, mulai {fusionFee0}, dan biaya itu dibakar selamanya. Hasil tingkat tinggi yang baru perlu istirahat sebentar sebelum bisa difusi atau dijual lagi.'] },
    { id: 'trade', title: 'Dagang', lead: 'Pasar adalah tempat distrik bertemu.',
      body: ['Jual cap bebas apa pun untuk SOL, USDC, atau SKR. Cap menunggu di escrow — pembeli dapat cap, kamu dapat bayaran, dalam satu transaksi. Biaya listing {listingFee}.',
        'Di setiap penjualan, {marketFee} untuk kota dan {royalty} untuk seniman. Sebagian bagian kota dipakai membeli kembali $CG lalu membakarnya, jadi setiap transaksi membuat koin sedikit lebih langka.'] },
    { id: 'stake', title: 'Staking', lead: 'Biarkan cap dan koin bekerja saat kamu tidur.',
      body: ['Cap yang di-stake mendapat bagian dari pool harian. Makin langka dan tinggi levelnya, makin besar bagiannya; set distrik lengkap memberi bonus. Pool-nya dibagi bersama — tidak bertambah saat cap bertambah, jadi cap langka dan awal lebih berbobot.',
        '$CG juga bisa di-stake: fleksibel, atau dikunci 30, 90, atau 180 hari untuk pengali lebih besar (×{d30}, ×{d90}, ×{d180}). Keluar lebih awal membakar sebagian dana ({p30}/{p90}/{p180}).',
        'Cap yang di-stake terkunci: tidak bisa difusi, dijual, atau dibawa ke arena sampai ditarik.'] },
    { id: 'coin', title: 'Koin $CG', lead: 'Didapat di jalan, dibelanjakan di jalan.',
      body: ['$CG adalah koin kota. Studio tidak pernah menjualnya — kamu mendapatkannya dari misi harian dan mingguan, pertandingan dan musim arena, staking dan event, atau membelinya dari pemain lain.',
        'Kamu memakainya untuk pack, biaya fusi, taruhan arena, dan kosmetik. Pasokan harian terbatas dan mengikuti denyut kota: makin banyak yang dibakar, makin banyak ruang untuk koin baru — saat jalanan sepi, kerannya menutup.'] },
    { id: 'burn', title: 'Yang terbakar', lead: 'Kelangkaan menjaga nilai tetap di tembok.',
      body: ['Koin terbakar: setiap biaya fusi, sebagian besar harga pack yang dibayar dengan $CG, biaya listing, sebagian biaya pasar dan arena, serta denda keluar stake lebih awal dimusnahkan selamanya.',
        'Cap juga terbakar: setiap fusi mengubah tiga cap jadi satu, jadi pasokan tiap kelangkaan terus menyusut saat pemain naik. Makin tinggi tingkatnya, makin sedikit yang akan pernah ada.'] },
    { id: 'free', title: 'Cap gratis', lead: 'Kota menghargai yang rajin datang.',
      body: ['Misi membayar $CG setiap hari. Jaga streak 7 hari untuk cap gratis, selesaikan semua misi mingguan untuk cap yang lebih baik, dan capai tonggak besar — 500 kemenangan arena, satu set distrik lengkap — untuk hadiah langka. Staker ikut undian mingguan cap Rare–Epic.',
        'Cap gratis terikat ke dompetmu beberapa hari sebelum bisa dijual — untuk dimainkan, bukan untuk dijual cepat.'] },
  ],
  outro: 'Setiap aturan di tembok ini dijalankan oleh program di Solana — sama untuk semua.',
};

const fil: GuideCopy = {
  title: 'Paano gumagana ang lungsod',
  subtitle: 'Gabay-kalye sa Gutter City: caps, fusion, kalakalan, staking at ang barya na nagbubuklod sa lahat.',
  toc: 'Sa pader na ito',
  sections: [
    { id: 'collect', title: 'Mangolekta', lead: 'Bawat cap ay isang pahina ng kuwento ng distrito nito.',
      body: ['May {districts} distrito ang Gutter City, at bawat isa ay nagkukuwento sa siyam na cap — mula sa gasgas na zinc na Common hanggang sa kumikislap na Diamond. Isang cap bawat rarity, siyam na rarity bawat distrito.',
        'Sulit ang pagkumpleto ng distrito: bawat buong set ay nagpapalakas sa mga naka-stake mong cap, at ang pinakabihirang set ay karangalan sa leaderboard. Hindi sayang ang duplicate — gatong ito sa fusion.'] },
    { id: 'packs', title: 'Mga pack', lead: 'Bawat pack ay selyado on-chain at binubuksan gamit ang napapatunayang randomness.',
      body: ['Starter — {starter}, {starterChips} cap, isa bawat araw: ang pinakamadaling pasok sa lungsod. Standard — {standard} o {standardCg}, {standardChips} cap. Premium — {premium} o {premiumCg}, {premiumChips} cap na may siguradong Rare. Limited — {limited}, para sa mga distrito ng event lamang.',
        'May hangganan ang malas: may counter ang Standard at Premium na nagtitiyak ng Legend. Masusuri ang bawat pagbukas sa pahinang Verify — walang makapipili ng lalabas, kahit kami.'] },
    { id: 'fusion', title: 'Fusion', lead: 'Tatlong cap ng isang rarity ay nagiging isang cap ng susunod.',
      body: ['Hanggang Epic, laging gumagana ang fusion. Salit-salitan ang hakbang: para umakyat ng kalahating antas (Common → Common+) puwede ang kahit anong tatlong cap at mananatili ang resulta sa distrito ng unang cap; para umakyat ng buong antas (Common+ → Rare) dapat magkakapareho ang distrito ng tatlo.',
        'Mula Epic pataas lumalakas ang baha: puwedeng pumalya ang fusion, pero laging may isang materyal na bumabalik. Nagdadagdag ang Charge Booster ng +{boosterBonus} pp (hanggang {boosterCap}%) — nakukuha ito sa quests at arena, hindi ibinebenta.',
        'May maliit na bayad na $CG ang bawat fusion, simula {fusionFee0}, at sinusunog ang bayad na iyon habambuhay. Nagpapahinga muna ang mga bagong cap na mataas ang antas bago muling ma-fuse o mailista.'] },
    { id: 'trade', title: 'Kalakalan', lead: 'Ang palengke ang tagpuan ng mga distrito.',
      body: ['Ilista ang kahit anong libreng cap kapalit ng SOL, USDC o SKR. Naghihintay ang cap sa escrow — makukuha ng mamimili ang cap at ikaw ang bayad, sa iisang transaksyon. {listingFee} ang bayad sa paglista.',
        'Sa bawat benta, {marketFee} ang napupunta sa lungsod at {royalty} sa mga artista. Bahagi ng parte ng lungsod ay bumibili pabalik ng $CG at sinusunog ito, kaya bawat benta ay nagpapaunti nang kaunti sa barya.'] },
    { id: 'stake', title: 'Staking', lead: 'Pagtrabahuhin ang caps at barya habang natutulog ka.',
      body: ['Kumikita ang mga naka-stake na cap ng bahagi sa araw-araw na pool. Mas bihira at mas mataas ang level, mas malaki ang bahagi; may bonus ang kumpletong set ng distrito. Pinaghahatian ang pool — hindi ito lumalaki kapag dumami ang cap, kaya mas mabigat ang bihira at maagang cap.',
        'Puwede ring i-stake ang $CG: flexible, o naka-lock nang 30, 90 o 180 araw para sa mas malaking multiplier (×{d30}, ×{d90}, ×{d180}). Ang maagang pag-alis ay sumusunog ng bahagi ng stake ({p30}/{p90}/{p180}).',
        'Naka-lock ang cap na naka-stake: hindi ito ma-fuse, mailista o magamit sa arena hangga’t hindi mo binabawi.'] },
    { id: 'coin', title: 'Ang baryang $CG', lead: 'Kinikita sa kalye, ginagastos sa kalye.',
      body: ['Ang $CG ang barya ng lungsod. Hindi ito ibinebenta ng studio — kinikita ito sa araw-araw at lingguhang quests, laban at season sa arena, staking at events, o binibili sa ibang manlalaro.',
        'Ginagastos ito sa packs, bayad sa fusion, pusta sa arena at cosmetics. Limitado ang araw-araw na supply at sumusunod sa sigla ng lungsod: kapag mas maraming nasusunog, mas maraming puwang para sa bagong barya — at kapag tahimik ang kalye, sumasara ang gripo.'] },
    { id: 'burn', title: 'Ang nasusunog', lead: 'Ang kakapusan ang nagpapanatili ng halaga sa pader.',
      body: ['Nasusunog ang barya: bawat bayad sa fusion, malaking bahagi ng presyo ng packs na binili gamit ang $CG, bayad sa paglista, bahagi ng bayad sa palengke at arena at multa sa maagang pag-unstake ay tuluyang nawawala.',
        'Nasusunog din ang caps: bawat fusion ay ginagawang isa ang tatlo, kaya lumiliit ang supply ng bawat rarity habang umaakyat ang mga manlalaro. Kapag mas mataas ang antas, mas kaunti ang iiral.'] },
    { id: 'free', title: 'Libreng caps', lead: 'Ginagantimpalaan ng lungsod ang mga dumarating.',
      body: ['Nagbabayad ng $CG ang quests araw-araw. Panatilihin ang 7-araw na streak para sa libreng cap, tapusin lahat ng lingguhan para sa mas maganda, at abutin ang malalaking milestone — 500 panalo sa arena, kumpletong set ng distrito — para sa bihirang gantimpala. Kasali rin ang mga staker sa lingguhang raffle ng Rare–Epic caps.',
        'Nakatali muna sa wallet mo nang ilang araw ang libreng caps bago maibenta — para laruin, hindi para i-flip.'] },
  ],
  outro: 'Bawat patakaran sa pader na ito ay ipinatutupad ng mga programa sa Solana — pare-pareho para sa lahat.',
};

export const GUIDE_COPY: Record<string, GuideCopy> = { en, ru, es, pt, vi, id, fil };
