// Stable backend codes. Shared/overloaded codes deliberately use a broad, truthful summary;
// the original message, parameters and diagnostics remain available in ErrorNotice.
import type { MessageKey } from '@/shared/i18n';
export const API_ERROR_KEYS = {
  age_required: 'rights.ageRequired', age_denied: 'rights.ageDenied', age_declaration_invalid: 'rights.invalid',
  country_unknown: 'rights.countryUnknown', region_restricted: 'rights.regionRestricted', privacy_restricted: 'rights.privacyRestricted',
  request_conflict: 'rights.conflict', request_limit: 'rights.limit', request_closed: 'rights.closed', reauth_required: 'rights.reauth',

  already_claimed: 'failures.staking_AlreadyClaimed', already_revealed: 'failures.alreadyRevealed',
  arena_missing: 'failures.unavailable', bad_amount: 'failures.requestInvalid', bad_assumptions: 'failures.requestInvalid',
  bad_chip: 'failures.requestInvalid', bad_collection: 'failures.chip_core_InvalidCollection', bad_commit: 'failures.badCommit',
  bad_currency: 'failures.market_CurrencyMismatch', bad_emote: 'failures.unknownEmote', bad_materials: 'failures.threeMaterials',
  bad_nonce: 'failures.badNonce', bad_note: 'failures.requestInvalid', bad_payload: 'failures.requestInvalid',
  bad_pubkey: 'diagnostics.pubkey', bad_qty: 'failures.badQuantity', bad_request: 'failures.requestInvalid',
  bad_resolution: 'failures.requestInvalid', bad_sku: 'failures.chip_core_InvalidSku', bad_sort: 'failures.requestInvalid',
  bad_squad: 'failures.threeSquad', bad_tier: 'failures.staking_InvalidTier', chain_fulfilled: 'failures.chainFulfilled',
  chip_busy: 'failures.arena_ChipBusy', collection_mismatch: 'failures.collectionMismatch', commit_mismatch: 'failures.commitMismatch',
  config_missing: 'screens.errGameConfig', currency_not_accepted: 'failures.chip_core_CurrencyNotAccepted',
  daily_cap: 'failures.chip_core_DailyCapReached', duplicate_chip: 'failures.arena_DuplicateChip',
  duplicate_material: 'failures.chip_core_DuplicateMaterial', emission_missing: 'failures.unavailable',
  geo_blocked: 'failures.geoBlocked', guard_rail: 'failures.guardRail', handle_cooldown: 'failures.handleCooldown',
  human_check_unavailable: 'failures.humanUnavailable', invalid_handle: 'failures.invalidHandle',
  match_pending: 'failures.matchPending', match_tagged_out: 'failures.matchTaggedOut', material_not_free: 'failures.chip_core_ChipNotFree',
  need_asset: 'failures.needAsset', no_pass: 'failures.noPass', no_recipe: 'failures.chip_core_NoRecipe',
  no_season: 'failures.noSeason', not_a_player: 'failures.notPlayer', not_found: 'failures.notFound',
  not_owner: 'failures.market_NotOwner', pack_required: 'failures.emotePack', payment_consumed: 'failures.paymentUsed',
  payment_kind_mismatch: 'failures.paymentKind', payment_not_found: 'failures.paymentNotFound', payment_pending: 'failures.paymentPending',
  price_unavailable: 'failures.priceUnavailable', rarity_mismatch: 'failures.chip_core_MaterialRarityMismatch',
  ref_hash_mismatch: 'failures.paymentPayload', same_handle: 'failures.sameHandle', set_not_completed: 'failures.setIncomplete',
  slow_down: 'failures.slowDown', squad_too_weak: 'failures.arena_SquadTooWeak', starter_claimed: 'failures.chip_core_StarterAlreadyClaimed',
  tier_locked: 'failures.tierLocked', turnstile_failed: 'failures.humanFailed', unknown_chip: 'failures.unknownChip',
  unknown_kind: 'failures.chip_core_InvalidService', unknown_quest: 'failures.unknownQuest', use_handle_endpoint: 'failures.handleEndpoint',
  wager_is_on_chain: 'failures.wagerChain', unauthenticated: 'failures.unauthenticated', forbidden: 'failures.forbidden', csrf: 'failures.csrf',
  siws_malformed: 'failures.requestInvalid', siws_address: 'failures.siwsAddress', siws_nonce: 'failures.siwsNonce',
  siws_expired: 'failures.siwsExpired', siws_domain: 'failures.siwsDomain', siws_issued_at: 'failures.siwsTime', siws_signature: 'failures.siwsSignature',
  handle_invalid: 'failures.invalidHandle', handle_taken: 'failures.handleTaken', handle_reserved: 'failures.handleReserved', handle_blocked: 'failures.handleBlocked',
  rate_limited: 'failures.rateLimited', payload_too_large: 'failures.payloadLarge', bad_json: 'failures.requestInvalid', internal: 'failures.internal',
  unknown_archetype: 'failures.requestInvalid', bad_season: 'failures.requestInvalid', unknown_board: 'failures.requestInvalid',
} as const satisfies Record<string, MessageKey>;
