import { RouterProvider } from 'react-router-dom';
import { Providers } from './providers';
import { router } from './router';
// Webfonts (SEC-B4, SECURITY-AUDIT-2026-09-26.md): one generated stylesheet, self-hosted from
// `public/fonts/`, instead of sixteen `@fontsource/<family>/<subset>-<weight>.css` imports. Those
// per-subset files carry no `unicode-range`, so every subset of a family matched every character and the
// last `@font-face` won — Inter's cyrillic face was shadowed by latin (RU text fell back to the system
// sans, the exact defect the old import list meant to fix) and JetBrains Mono's latin face was shadowed
// by cyrillic (prices and addresses fell back too). `fonts.css` is generated by `npm run fonts:vendor`
// with the upstream ranges, so each script downloads only the subset it needs.
// `npm run fonts:check` + `src/shared/ui/fonts.test.ts` keep it honest.
import '@/shared/ui/fonts.css';
import '@/shared/ui/theme.css';
import '@/shared/ui/layout.css';
import '@/shared/ui/street-kit.css';
import '@/shared/ui/street-apply.css';
import { StreetFilters } from '@/shared/ui/street-filters';

export default function App() {
  return (
    <Providers>
      <StreetFilters />
      <RouterProvider router={router} />
    </Providers>
  );
}
