  // ---------------------------------------------------------------------
  // LINKS — the only place to edit before launch. '#' renders as a dead,
  // visibly disabled link on purpose: no handle is linked before we own it.
  //
  // The social/community channels are NOT listed here: which networks the page
  // talks about lives in one place, the CHANNELS list in scripts/landing/build.py,
  // because the same list also renders the anchors this resolver reads. A second
  // hand-written copy of those names is exactly what used to live on this line,
  // and the two could disagree invisibly — a channel rendered without a LINKS
  // entry kept href="#" and looked, to a reviewer, like a link still coming.
  // build.py splices the generated entries in at the marker below.
  // ---------------------------------------------------------------------
  const LINKS = {
    app: 'https://app.guttercaps.gg',
    api: 'https://api.guttercaps.gg/v1',
/*__CHANNELS__*/
  };
  // The legal documents are served by the app itself (client/src/features/legal/), so they are derived
  // from `app` rather than written out again: at launch the domain changes in exactly one place, and a
  // ToS link left on the old host is the kind of bug a store rejection is filed for.
  for (const [key, path] of [['terms', '/legal/terms'], ['privacy', '/legal/privacy'], ['presale', '/preorder']]) {
    LINKS[key] = LINKS.app + path;
  };
  document.querySelectorAll('[data-link]').forEach((a) => {
    const href = LINKS[a.dataset.link];
    if (href && href !== '#') { a.href = href; return; }
    a.setAttribute('aria-disabled', 'true');
    a.title = 'coming soon';
    a.addEventListener('click', (e) => e.preventDefault());
  });

  function fireSpray(btn) {
    btn.classList.add('fired');
    setTimeout(() => btn.classList.remove('fired'), 400);
  }

  // Ambient cursor/touch paint trail — throttled, off for reduced motion.
  (function () {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const colors = ['#FF2E8A', '#16E5D9', '#B6FF3C', '#FF7A1A'];
    let last = 0;
    function spawn(x, y) {
      const dot = document.createElement('div');
      dot.className = 'paint-dot';
      dot.style.left = (x - 2) + 'px'; dot.style.top = (y - 2) + 'px';
      dot.style.background = colors[Math.floor(Math.random() * colors.length)];
      document.body.appendChild(dot);
      setTimeout(() => dot.remove(), 700);
    }
    function onMove(x, y) { const now = performance.now(); if (now - last < 45) return; last = now; spawn(x, y); }
    window.addEventListener('mousemove', (e) => onMove(e.clientX, e.clientY), { passive: true });
    window.addEventListener('touchmove', (e) => { const t = e.touches[0]; if (t) onMove(t.clientX, t.clientY); }, { passive: true });
  })();

  // Hero letters spray in one by one.
  (function () {
    const el = document.getElementById('hero-title');
    'GUTTERCAPS'.split('').forEach((ch, i) => {
      const span = document.createElement('span');
      span.className = 'spray-letter' + (i >= 6 ? ' accent' : '');
      span.style.animationDelay = (i * 55) + 'ms';
      span.textContent = ch;
      el.appendChild(span);
    });
  })();

  // Street-lamp bulbs inside every glow.
  (function () {
    document.querySelectorAll('.lamp-glow').forEach((glow) => {
      const bulb = document.createElement('div');
      bulb.className = 'lamp-bulb';
      const rect = glow.style.background.match(/rgba?\(([^)]+)\)/);
      bulb.style.color = rect ? 'rgba(' + rect[1].split(',').slice(0, 3).join(',') + ',1)' : '#fff';
      bulb.style.left = '50%'; bulb.style.top = '50%';
      glow.appendChild(bulb);
    });
  })();

  // ---------------------------------------------------------------------
  // Data — generated by scripts/landing/build.py from content.py, which
  // mirrors packages/economy (checked by scripts/landing/check.py).
  // ---------------------------------------------------------------------
/*__DATA__*/
/*__STEP_ART__*/

  // ---------------------------------------------------------------------
  // All seven dictionaries are validated at build time. Query > saved > browser.
  let LANG = 'en';
  const financialCells = [...document.querySelectorAll('.legend b, .bar b, .fee-table .num')].map((el) => [el, el.textContent]);
  const metaDesc = document.querySelector('meta[name="description"]');
  const isLang = (l) => typeof l === 'string' && Object.hasOwn(I18N, l);
  function normalizeLang(l) {
    const code = String(l || '').toLowerCase().split(/[-_]/)[0];
    return code === 'tl' ? 'fil' : isLang(code) ? code : null;
  }
  function detectLang() {
    const query = normalizeLang(new URLSearchParams(location.search).get('lang'));
    if (query) return query;
    try { const saved = normalizeLang(localStorage.getItem('gc.landing.lang')); if (saved) return saved; } catch { /* private mode */ }
    for (const lang of navigator.languages || [navigator.language]) {
      const detected = normalizeLang(lang); if (detected) return detected;
    }
    return 'en';
  }
  function tr(k, vars = {}) {
    return I18N[LANG][k].replace(/\{(\w+)\}/g, (whole, key) => Object.hasOwn(vars, key) ? String(vars[key]) : whole);
  }
  function num(n) { return new Intl.NumberFormat(LANG_TAGS[LANG]).format(n); }
  function percent(value) { return new Intl.NumberFormat(LANG_TAGS[LANG], { style: 'percent', maximumFractionDigits: 2 }).format(value); }
  function usd(value) { return new Intl.NumberFormat(LANG_TAGS[LANG], { style: 'currency', currency: 'USD' }).format(value); }

  function setLang(lang) {
    LANG = normalizeLang(lang) || 'en';
    document.documentElement.lang = LANG_TAGS[LANG];
    document.documentElement.dataset.lang = LANG;
    document.querySelectorAll('[data-i18n],[data-i18n-html]').forEach((el) => {
      const k = el.dataset.i18n || el.dataset.i18nHtml;
      const v = tr(k);
      if (v === undefined) return;
      if (el.dataset.i18nHtml !== undefined) el.innerHTML = v; else el.textContent = v;
    });
    document.querySelectorAll('[data-i18n-aria]').forEach((el) => el.setAttribute('aria-label', tr(el.dataset.i18nAria)));
    document.title = tr('meta.title');
    for (const prefix of ['og', 'twitter']) {
      const title = document.querySelector(`meta[property="${prefix}:title"],meta[name="${prefix}:title"]`);
      const desc = document.querySelector(`meta[property="${prefix}:description"],meta[name="${prefix}:description"]`);
      if (title) title.content = tr('meta.title');
      if (desc) desc.content = tr('meta.desc');
    }
    document.querySelector('meta[property="og:locale"]').content = LANG_TAGS[LANG].replace('-', '_');
    document.querySelectorAll('script[type="application/ld+json"]').forEach((el) => {
      const data = JSON.parse(el.textContent);
      if (data['@type'] === 'FAQPage') data.mainEntity.forEach((entry, i) => { entry.name = tr('faq.q' + i); entry.acceptedAnswer.text = tr('faq.a' + i); });
      if (data['@type'] === 'VideoGame') data.description = tr('meta.desc');
      el.textContent = JSON.stringify(data);
    });
    if (metaDesc) metaDesc.content = tr('meta.desc');
    document.querySelectorAll('.lang-toggle button').forEach((b) => b.setAttribute('aria-pressed', String(b.dataset.lang === LANG)));
    try { const url = new URL(location.href); url.searchParams.set('lang', LANG); history.replaceState(null, '', url.href); } catch { /* static file / restricted history */ }
    try { localStorage.setItem('gc.landing.lang', LANG); } catch (e) { /* ignore */ }
    for (const [el, value] of financialCells) {
      if (/^[−-]?[\d.]+\s*%$/.test(value)) el.textContent = percent(Number(value.replace('%', '').replace('−', '-')) / 100);
      else if (value.endsWith('$CG')) el.textContent = num(Number(value.replace('$CG', '').trim())) + ' $CG';
      else if (value.startsWith('$')) el.textContent = value.split(' – ').map((v) => usd(Number(v.replace('$', '')))).join(' – ');
    }
    renderHowto();
    renderPacks();
    renderStats(lastStats);
    renderDistricts();
    renderTiers();
    document.querySelectorAll('a[aria-disabled="true"]').forEach((a) => { a.title = UI[LANG].comingSoon; });
    document.querySelector('nav').setAttribute('aria-label', UI[LANG].primaryNav);
    document.querySelector('.lang-toggle').setAttribute('aria-label', tr('nav.language'));
    document.querySelectorAll('[data-link="app"],[data-link="terms"],[data-link="privacy"]').forEach((a) => { const url = new URL(LINKS[a.dataset.link]); url.searchParams.set('lang', LANG); a.href = url.href; });
  }
  document.querySelectorAll('.lang-toggle button').forEach((b) => b.addEventListener('click', () => setLang(b.dataset.lang)));

  function hexToRgba(hex, a) {
    const v = hex.replace('#', '');
    const n = parseInt(v.length === 3 ? v.split('').map((c) => c + c).join('') : v, 16);
    return 'rgba(' + ((n >> 16) & 255) + ',' + ((n >> 8) & 255) + ',' + (n & 255) + ',' + a + ')';
  }

  const STEP_KEYS = ['connect', 'pack', 'reveal', 'fuse', 'play'];
  function renderHowto() {
    const wrap = document.getElementById('howto');
    wrap.innerHTML = HOWTO.map((s, i) => {
      const [h, p, f] = ['h', 'p', 'f'].map((part) => tr(`how.${i}.${part}`));
      const src = STEP_ART['step-' + STEP_KEYS[i]] || '';
      const photo = src ? '<img class="step-photo" src="' + src + '" alt="" aria-hidden="true" loading="lazy" decoding="async">' : '';
      return '<li class="step" style="--step-color:' + s.color + ';--step-glow:' + s.glow + '">' + photo +
        '<div class="step-num" aria-hidden="true">' + (i + 1) + '</div><h3>' + h + '</h3><p>' + p + '</p><span class="step-fact">' + f + '</span></li>';
    }).join('');
  }

  function renderPacks() {
    const wrap = document.getElementById('packs-grid');
    wrap.innerHTML = PACKS.map((p, i) => {
      const name = UI[LANG]['pack' + i], tag = tr('pack.tag' + i);
      const floor = p.floor, caps = p.chips;
      const lines = [tr('pack.caps', { n: caps, rarity: tierName(floor) })];
      if (i === 0) lines.push(tr('pack.lock', { days: 7 }), tr('pack.noPity'));
      else {
        lines.push(tr('pack.hard', { rarity: tierName(6), n: p.hardAt }));
        lines.push(i === 3 ? tr('pack.limit', { n: p.dailyCap }) : tr('pack.soft', { n: p.softStart }));
      }
      lines.push(i === 3 ? tr('pack.pool') : 'SOL · USDC · SKR' + (p.cg ? ' · $CG' : ''));
      const alt = p.cg ? tr('pack.or', { amount: num(Number(p.cg.replace(/[^0-9]/g, ''))) + ' $CG' }) : '';
      const art = (typeof PACK_ART !== 'undefined' && PACK_ART[p.art])
        ? '<img class="pack-art" src="' + PACK_ART[p.art] + '" alt="' + name + '" loading="lazy" decoding="async">' : '';
      return '<div class="pack" style="--pack-color:' + p.color + ';--pack-glow:' + p.glow + '">' + art +
        '<span class="pack-tag">' + tag + '</span><span class="pack-name">' + name + '</span>' +
        '<span class="pack-price">' + usd(Number(p.price.slice(1))) + '<small>' + alt + '</small></span>' +
        '<ul>' + lines.map((l) => '<li>' + l + '</li>').join('') + '</ul></div>';
    }).join('');
  }

  function tierName(i) { return UI[LANG]['rarity' + i]; }

  // Charge meter and permits re-render on every language change.
  function renderTiers() {
    const wrap = document.getElementById('meterRows');
    wrap.replaceChildren();
    [...TIERS].reverse().forEach((t, idx) => {
      const rank = TIERS.length - 1 - idx;
      const row = document.createElement('div');
      row.className = 'meter-row' + (rank === 8 ? ' meter-row--peak' : '');
      row.style.setProperty('--tier-color', t.color);
      row.style.setProperty('--dot-size', (8 + rank * 1.6) + 'px');
      row.style.setProperty('--dot-glow', (5 + rank * 2.4) + 'px');
      row.innerHTML =
        '<span class="meter-dot"></span>' +
        '<span class="m-name" style="font-size:' + (14 + rank * 1.7) + 'px">' + tierName(rank) + '</span>' +
        '<span class="m-odds">' + percent(parseFloat(t.odds) / 100) + '</span>' +
        '<span class="m-level">' + tr('level', { n: num(t.level) }) + '<span class="m-power">⚡ ' + t.power + ' · ⚖ ' + t.weight + '</span></span>';
      wrap.appendChild(row);
    });

    // Same tier table, not a second source of truth.
    const permits = document.getElementById('permitGrid');
    permits.replaceChildren();
    TIERS.forEach((t, i) => {
      const card = document.createElement('div');
      card.className = 'permit';
      card.style.setProperty('--p-color', t.color);
      card.innerHTML = '<div class="p-tier">' + tierName(i) + '</div><div class="p-odds">' + percent(parseFloat(t.odds) / 100) + '</div><div class="p-level">' + tr('level', { n: num(t.level) }) + ' · ' + t.power + '⚡</div>';
      permits.appendChild(card);
    });
  }

  // Live counters from the indexer (backend GET /v1/stats). Never faked:
  // if the API is unreachable the section says so.
  let lastStats = null;
  function renderStats(s) {
    const status = document.getElementById('stats-status');
    const loc = LANG_TAGS[LANG];
    if (!s) { status.textContent = tr('stats.offline'); return; }
    document.querySelectorAll('[data-stat]').forEach((el) => {
      const v = s[el.dataset.stat];
      el.classList.remove('pending');
      el.textContent = typeof v === 'number' ? v.toLocaleString(loc) : '—';
    });
    status.textContent = tr('stats.slot', { n: num(Number(s.lastSlot || 0)) });
  }
  (function () {
    if (typeof fetch !== 'function' || typeof AbortController !== 'function') return;
    const ctrl = new AbortController();
    setTimeout(() => ctrl.abort(), 4000);
    fetch(LINKS.api + '/stats', { signal: ctrl.signal })
      .then((r) => (r.ok ? r.json() : null))
      .then((s) => { lastStats = s; renderStats(s); })
      .catch(() => renderStats(null));
  })();

  // ---------------------------------------------------------------------
  // ART SLOTS — every cap is { name, desc } and renders as a placeholder
  // ring; add an "img" field per cap when final art arrives.
  // ---------------------------------------------------------------------
/*__COLLECTIONS__*/
  function renderDistricts() {
    const wrap = document.getElementById('districts');
    const scrolls = [...wrap.querySelectorAll('.chip-row')].map((row) => row.scrollLeft);
    wrap.replaceChildren();
    COLLECTIONS.forEach((source, ci) => {
      const col = LANG !== 'en' ? { ...source, ...LORE[LANG]['d' + ci], caps: source.caps.map((cap, ri) => ({ ...cap, ...LORE[LANG]['c' + ci + 'r' + ri] })) } : source;
      const div = document.createElement('div');
      div.className = 'district';
      div.style.setProperty('--district-color', col.color);
      const art = (typeof DISTRICT_ART !== 'undefined' && DISTRICT_ART[col.num]) ? DISTRICT_ART[col.num] : null;
      const geo = (typeof DISTRICT_ART_GEO !== 'undefined') ? DISTRICT_ART_GEO : { tile: 118, gut: 8, pad: 12 };
      const sheet = geo.pad * 2 + geo.tile * 3 + geo.gut * 2;
      let row = '';
      col.caps.forEach((cap, i) => {
        const t = TIERS[i];
        const size = 138, glow = 6 + i * 3, rim = i === 8 ? 3 : 4;
        const circleStyle = 'width:' + size + 'px;height:' + size + 'px;--tier-color:' + t.color + ';--tier-bg:' + hexToRgba(t.color, 0.18) + ';--tier-glow:' + hexToRgba(t.color, 0.5) + ';--rim-w:' + rim + 'px;--glow:' + glow + 'px;';
        // real art: sprite this cap's tile out of the district contact sheet
        // (zero extra bytes — the sheet is already inlined for the chip sprites)
        let sprite = '';
        if (art) {
          const scale = size / geo.tile;
          const tx = geo.pad + (i % 3) * (geo.tile + geo.gut);
          const ty = geo.pad + Math.floor(i / 3) * (geo.tile + geo.gut);
          sprite = '<span class="chip-sprite" style="background-image:url(' + art + ');background-position:' +
            (-tx * scale).toFixed(2) + 'px ' + (-ty * scale).toFixed(2) + 'px;background-size:' +
            (sheet * scale).toFixed(2) + 'px ' + (sheet * scale).toFixed(2) + 'px;" aria-hidden="true"></span>';
        }
        const inner = cap.img
          ? '<img src="' + cap.img + '" alt="' + cap.name + '" loading="lazy" decoding="async">'
          : sprite
            ? sprite
            : '<span class="chip-mono" style="font-size:' + Math.round(size * 0.32) + 'px;">' + col.name.charAt(0) + '</span>';
        row += '<div class="chip-slot' + (i === 8 ? ' chip-slot--diamond' : '') + '">' +
          '<div class="chip-circle" style="' + circleStyle + '">' + inner + '</div>' +
          '<span class="chip-tier" style="color:' + t.color + '">' + tierName(i) + '</span>' +
          '<span class="chip-name">' + cap.name + '</span>' +
          '<span class="chip-desc">' + cap.desc + '</span></div>';
      });
      div.innerHTML =
        '<div class="district-head"><span class="district-num">' + col.num + '</span>' +
        '<div><h3 class="district-name">' + col.name + '</h3><span class="district-meta">' + col.district + ' · ' + col.theme + '</span></div></div>' +
        '<p class="district-history">' + col.history + '</p><div class="chip-row">' + row + '</div>';
      wrap.appendChild(div);
      div.querySelector('.chip-row').scrollLeft = scrolls[ci] || 0;
    });
  }

  // ---------------------------------------------------------------------
  // PHOTO WALLS — backdrop reveal on scroll + cursor light in the hero.
  // Both are decorative: they switch on with JS, stay off without it, and
  // freeze entirely under prefers-reduced-motion.
  // ---------------------------------------------------------------------
  (function () {
    const photos = document.querySelectorAll('.wall-photo');
    if (!photos.length) return;
    if (matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) {
      photos.forEach((p) => p.classList.add('on'));
      return;
    }
    const io = new IntersectionObserver((entries) => entries.forEach((e) => {
      if (e.isIntersecting) { e.target.classList.add('on'); io.unobserve(e.target); }
    }), { rootMargin: '160px' });
    photos.forEach((p) => io.observe(p));
  })();

  (function () {
    const hero = document.querySelector('.hero');
    if (!hero || matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    if (hero.querySelector('.puddle-glow')) return;
    const glow = document.createElement('div');
    glow.className = 'puddle-glow';
    hero.appendChild(glow);
    let raf = 0;
    hero.addEventListener('pointermove', (e) => {
      if (raf) return;
      raf = requestAnimationFrame(() => {
        const r = hero.getBoundingClientRect();
        glow.style.setProperty('--px', (((e.clientX - r.left) / r.width) * 100).toFixed(1) + '%');
        glow.style.setProperty('--py', (((e.clientY - r.top) / r.height) * 100).toFixed(1) + '%');
        raf = 0;
      });
    }, { passive: true });
  })();

  setLang(detectLang());
